# aliases
alias .net="dotnet"
alias c="code"
alias dc="docker compose"
alias la="ls -a"
alias m="git checkout master"
alias mvp="mvn clean package -U"
alias net="dotnet"
alias nr="npm run"
alias p="cd ~/Projects"
alias pls="sudo"
alias pull="git pull --prune"
alias push="git push"
